services:
  - type: web
    name: mapmate-backend
    env: python
    buildCommand: "cd mapmate_backend && pip install -r requirements.txt"
    startCommand: "cd mapmate_backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

  - type: web
    name: mapmate-frontend
    env: node
    buildCommand: "cd mapmate_frontend && npm install && npm run build"
    startCommand: "npm run preview --prefix mapmate_frontend -- --port $PORT --host 0.0.0.0"
