/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#00213e",
        "surface-container-high": "#201f1f",
        "tertiary-fixed-dim": "#51a7fe",
        "primary": "#8ff5ff",
        "background": "#0e0e0e",
        "primary-dim": "#00deec",
        "secondary": "#2ff801",
        "on-primary-fixed-variant": "#005e64",
        "tertiary-dim": "#4aa2f9",
        "on-secondary-fixed-variant": "#0d6200",
        "secondary-dim": "#2be800",
        "surface-tint": "#8ff5ff",
        "surface": "#0e0e0e",
        "on-error-container": "#ffa8a3",
        "error": "#ff716c",
        "surface-container-lowest": "#000000",
        "inverse-primary": "#006a71",
        "secondary-fixed-dim": "#2be800",
        "primary-fixed": "#00eefc",
        "on-background": "#ffffff",
        "surface-container-highest": "#262626",
        "surface-dim": "#0e0e0e",
        "secondary-fixed": "#2ff801",
        "primary-container": "#00eefc",
        "tertiary-container": "#4aa2f9",
        "on-surface": "#ffffff",
        "outline-variant": "#494847",
        "on-secondary-container": "#e7ffd9",
        "secondary-container": "#106e00",
        "on-surface-variant": "#adaaaa",
        "surface-container-low": "#131313",
        "surface-variant": "#262626",
        "on-primary-fixed": "#003f43",
        "on-tertiary-fixed-variant": "#003b68",
        "surface-bright": "#2c2c2c",
        "outline": "#777575",
        "surface-container": "#1a1919",
        "primary-fixed-dim": "#00deec",
        "error-container": "#9f0519",
        "inverse-on-surface": "#565554",
        "on-tertiary-fixed": "#001930",
        "tertiary-fixed": "#72b5ff",
        "error-dim": "#d7383b",
        "on-secondary-fixed": "#064200",
        "inverse-surface": "#fcf8f8",
        "on-error": "#490006",
        "on-secondary": "#0b5800",
        "on-tertiary": "#002e52",
        "on-primary-container": "#005359",
        "tertiary": "#65afff",
        "on-primary": "#005d63"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
